### PR TITLE
Added Korean localization

### PR DESCRIPTION
**Pull request by HyeongminKim**
I am sending a PR with Korean localization.

스크린샷 2021-04-01 18 53 34

### CODE REVIEW

**Comment by niw** [comment]
@HyeongminKim Thank you for the translations. Let me evaluate them and once I can confirm them, I will merge this!

**Comment by niw** [comment]
@HyeongminKim Thank you for the translation! I will check the wording consistency with Apple’s glossary shortly and merge this.

**Review by niw — COMMENTED** [review]
Since localizable.strings is recognized as binary file on GitHub, I will post review and questions as a comment.
Please advice me if I am wrong, I don’t speak Korean but checked other common wording and what Apple users for typical sentences in the app.

```
/* A status menu item to set automatically check for updates. */
"STATUS_MENU_ITEM_AUTOMATICALLY_CHECK_FOR_UPDATES_MENU_ITEM" = "자동으로 업데이트 확인";
```
`"자동 업데이트 확인"` would be better? I see this wording in various applications.

```/* A status menu item to use function key events. */
"STATUS_MENU_ITEM_FUNCTION_KEY_EVENT_MENU_ITEM" = "ESC와 F1, F2 등 기능키"
```
`"ESC와 F1, F2 등의 키"` would be better?

```
/* A status menu item to use screen flash. */
"STATUS_MENU_ITEM_SCREEN_FLASH_MENU_ITEM" = "화면 깜빡임";
```
Wondering if `"화면 플래시"` would make more sense or not?

```
/* A status menu item to show icon in menu bar. */
"STATUS_MENU_ITEM_SHOW_STATUS_BAR_ICON_MENU_ITEM" = "HapticKey를 메뉴바에 보이기";
```
`"메뉴 막대에서 HapticKey 상태 보기"` is what apple is using for the other icons on menu items in their System Preferences.app, probably this wording is better?

**Comment by HyeongminKim** [comment]
1. The string you suggested is missing investigation, but it shouldn't be a problem as anyone can understand it.
2. Sure
3. `"깜빡임"`<sup>1</sup> doesn't look bad in my opinion, but I'll leave it to your choice. (However, I will attach a screenshot of “Flash the screen when an alert sound occurs” in the Audio section located in the Accessibility of System Preferences.)
스크린샷 2021-04-28 20 03 54

4. I think `"HapticKey를 메뉴바에 보이기"` would be better.

### ps
1. In order to avoid confusion, I will attach the tedious grammar because the strings in the system configuration and the strings uploaded to GitHub are different. Both “깜빡하다” and “깜박하다” were recognized as correct expressions by the National Institute of the Korean Language.
> The standard Korean dictionary suggests '깜빡하다', which means "memory or consciousness is temporarily blurred," as "it gives a stronger feeling than '깜박하다'."  Therefore, '깜박하다' and '깜빡하다' are both correct expressions. (Untranslated sentences can be found [here](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=84679).)

**Comment by niw** [comment]
Appreciate for your feedback.

> 1. The string you suggested is missing investigation, but it shouldn't be a problem as anyone can understand it.

If it’s not common wording, then ignore my suggestion.
To be honest, I found that wording in apps that is using Sparkle or a similar update mechanism, but really not sure that’s common in in the apps.

> 3. `"깜빡임"`1 doesn't look bad in my opinion, but I'll leave it to your choice. (However, I will attach a screenshot of “Flash the screen when an alert sound occurs” in the Audio section located in the Accessibility of System Preferences.)
> 스크린샷 2021-04-28 20 03 54

Ah, I see! Nice finding in Accessibility preferences pane. Let’s keep it as-is.

> 4. I think `"HapticKey를 메뉴바에 보이기"` would be better.

OK, thanks! Let’s keep it as-is.

**Comment by niw** [comment]
Since my suggestion is really minor, I merged your current change and update it later on `master`. Thank you!

**Pull request merged**
