### PR TITLE
Polish localization

### PR DESCRIPTION
**Pull request by jcabak**
- added screenshot to readme
 - added polish localization (preview below)
 
2021-10-27 o 12 58 21

### CODE REVIEW

**Comment by niw** [comment]
@jcabak Thank you for the contribution. I can accept the patch however, current change includes modification of `README.md` and adding `screenshot.png` to the project root, which is not preferred and unrelated for adding Polish translation. Could you remove these change from the patch?

**Comment by jcabak** [comment]
Fixed @niw

**Comment by niw** [comment]
Thank you, I will review it soon!

**Comment by niw** [comment]
I checked Apple’s translations for Polish for some common words used in macOS applications, which is available as "Glossaries" on developer portal and I have a few questions.

> Check for Updates
> Sprawdź dostępność aktualizacji

Apple translated this action as `Sprawdzaj dostępność uaktualnień`. Is it better?

> Quite HapticKey
> Wyjdź z HapticKey

Apple is using `Zakończ` for many application’s "Quit (application name)" action, so `Zakończ HapticKey` would be better for consistency?

> Show HapticKey in Menu Bar
> Pokaż HapticKey w pasku menu

Apple is using `Pokazuj ... na pasku menu` for similar action. So `Pokazuj HapticKey na pasku menu` is better?

> Sound Effect
> Efekt dźwiękowy

Apple is using `Efekty dźwiękowe` for this word, is it better?

Note that I don’t have Polish skill so can’t tell which is better yet prefer to use common wording as a macOS application. If you can review these words, that would be really helpful!

**Comment by lucek8123** [comment]
1. `Sprawdzaj dostępność uaktualnień` is for regular action, but `sprawdź dostępność uaktualnień` is for now action. I think `Sprawdź dostępność aktualizacji` is better in this case. 
2. `Zakończ HapticKey` is better. 
3. `Pokazuj HapticKey na pasku menu` is better 
4. `Efekty dźwiękowe` is better.

**Comment by jcabak** [comment]
I checked with several applications in Polish so now it should be consistent.

I read @niw and @lucek8123 suggestions and you have right.
the only thing I don't agree -  `Efekt dźwiękowy` is better because it is singular, `Efekty dźwiękowe` is plural.

**Comment by lucek8123** [comment]
I am from Poland and the plural form(`Efekty dźwiękowe`) is better, because it sounds better.

**Comment by jcabak** [comment]
I am also from Poland but plural form `Efekty dźwiękowe` could be confusing because it mean it will be more than one sound**s** effect**s**.

**Comment by niw** [comment]
Yeah, for now, the original English label is "Sound Effect" actually (not plural.) If there are any concerns to have it as a singular, I think should be fine.

**Pull request merged**
